// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEZFrnhZmJYVomfupctloTTv8zUtJkw1Y',
    appId: '1:65316680807:android:0b389af9c4b39dad61d0c2',
    messagingSenderId: '65316680807',
    projectId: 'myapp-152ca',
    storageBucket: 'myapp-152ca.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeggiEVX62fDtSSsXirKRr76HvFDKZCII',
    appId: '1:65316680807:web:85ecd00fb08d354461d0c2',
    messagingSenderId: '65316680807',
    projectId: 'myapp-152ca',
    authDomain: 'myapp-152ca.firebaseapp.com',
    storageBucket: 'myapp-152ca.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeggiEVX62fDtSSsXirKRr76HvFDKZCII',
    appId: '1:65316680807:web:85ecd00fb08d354461d0c2',
    messagingSenderId: '65316680807',
    projectId: 'myapp-152ca',
    authDomain: 'myapp-152ca.firebaseapp.com',
    storageBucket: 'myapp-152ca.firebasestorage.app',
  );

}