// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb0194ySg1ZrVg164Xkd7OtRUpqbkR6Wc',
    appId: '1:982589165007:web:6933af0d6a1344e97f16ba',
    messagingSenderId: '982589165007',
    projectId: 'flutter-auth-app-6e113',
    authDomain: 'flutter-auth-app-6e113.firebaseapp.com',
    storageBucket: 'flutter-auth-app-6e113.firebasestorage.app',
    measurementId: 'G-MPVZPJP2Y8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8tA-3he6C93PQC4IBKGgagzE62ZFTgh8',
    appId: '1:982589165007:android:a62570c25ffb13387f16ba',
    messagingSenderId: '982589165007',
    projectId: 'flutter-auth-app-6e113',
    storageBucket: 'flutter-auth-app-6e113.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIdqf32KTd1nz3hULYuoMgjzkyxT8wn1M',
    appId: '1:982589165007:ios:b7f561b62a02ed717f16ba',
    messagingSenderId: '982589165007',
    projectId: 'flutter-auth-app-6e113',
    storageBucket: 'flutter-auth-app-6e113.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuthApp',
  );
}
